cd $HOME/myexpos/spl

echo "os-startup"
./spl ./spl_progs/S-27/os-startup.spl
echo "boot module"
./spl ./spl_progs/S-27/boot_module.spl

echo "exception"
./spl ./spl_progs/S-27/exception.spl
echo "timer"
./spl ./spl_progs/S-27/timer.spl
echo "disk"
./spl ./spl_progs/S-27/disk.spl
echo "console"
./spl ./spl_progs/S-27/console.spl

echo "int4"
./spl ./spl_progs/S-27/int4.spl
echo "int5"
./spl ./spl_progs/S-27/int5.spl
echo "int6"
./spl ./spl_progs/S-27/int6.spl
echo "int7"
./spl ./spl_progs/S-27/int7.spl
echo "int8"
./spl ./spl_progs/S-27/int8.spl
echo "int9"
./spl ./spl_progs/S-27/int9.spl
echo "int10"
./spl ./spl_progs/S-27/int10.spl
echo "int11"
./spl ./spl_progs/S-27/int11.spl
echo "int12"
./spl ./spl_progs/S-27/int12.spl
echo "int13"
./spl ./spl_progs/S-27/int13.spl
echo "int14"
./spl ./spl_progs/S-27/int14.spl
echo "int15"
./spl ./spl_progs/S-27/int15.spl
echo "int16"
./spl ./spl_progs/S-27/int16.spl
echo "int17"
./spl ./spl_progs/S-27/int17.spl

echo "mod6"
./spl ./spl_progs/S-27/mod6.spl
echo "mod5"
./spl ./spl_progs/S-27/mod5.spl
echo "mod4"
./spl ./spl_progs/S-27/mod4.spl
echo "mod3"
./spl ./spl_progs/S-27/mod3.spl
echo "mod2"
./spl ./spl_progs/S-27/mod2.spl
echo "mod1"
./spl ./spl_progs/S-27/mod1.spl
echo "mod0"
./spl ./spl_progs/S-27/mod0.spl

cd $HOME/myexpos/expl
echo "idle"
./expl ../spl/spl_progs/S-27/idle.expl
echo "shell"
./expl ../spl/spl_progs/S-27/shell.expl
echo "init"
./expl ../spl/spl_progs/S-27/init.expl
echo "pid"                               
./expl ../spl/spl_progs/S-27/pid.expl
echo "fork"                               
./expl ../spl/spl_progs/S-27/fork.expl
echo "create"                               
./expl ../spl/spl_progs/S-27/create.expl
echo "odd"                               
./expl ../spl/spl_progs/S-27/odd.expl
echo "even"                               
./expl ../spl/spl_progs/S-27/even.expl
echo "lu"                               
./expl ../spl/spl_progs/S-27/lu.expl
echo "ru"                               
./expl ../spl/spl_progs/S-27/ru.expl
echo "ls"                               
./expl ../spl/spl_progs/S-27/ls.expl
echo "rm"                               
./expl ../spl/spl_progs/S-27/rm.expl
echo "cat"                               
./expl ../spl/spl_progs/S-27/cat.expl
echo "cp"                               
./expl ../spl/spl_progs/S-27/cp.expl
echo "as2"                               
./expl ../spl/spl_progs/S-27/as2.expl
echo "as3"                               
./expl ../spl/spl_progs/S-27/as3.expl
echo "pgm1.expl"                               
./expl ../spl/spl_progs/S-27/pgm1.expl
echo "as4"                               
./expl ../spl/spl_progs/S-27/as4.expl
echo "pgm2.expl"                               
./expl ../spl/spl_progs/S-27/pgm2.expl
echo "m_merge"                               
./expl ../spl/spl_progs/S-27/m_merge.expl
echo "m_sort.expl"                               
./expl ../spl/spl_progs/S-27/m_sort.expl
echo "m_store"                               
./expl ../spl/spl_progs/S-27/m_store.expl
echo "merge.expl"                               
./expl ../spl/spl_progs/S-27/merge.expl

cd $HOME/myexpos/xfs-interface
./xfs-interface run ../spl/spl_progs/S-27/run.sh

echo "COMPLETED"
